# Generated by Django 5.2.4 on 2025-09-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersposts',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
